# Generated by Django 5.2.8 on 2025-11-30 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='images')),
                ('desc', models.TextField()),
                ('price', models.PositiveBigIntegerField()),
                ('bedroom', models.CharField(default=1)),
                ('bathroom', models.PositiveSmallIntegerField(default=1)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('floor', models.PositiveSmallIntegerField(default=2)),
                ('parking', models.PositiveSmallIntegerField(default=2)),
                ('room', models.PositiveSmallIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='main.category')),
            ],
        ),
    ]
